Message: '&8[&cCarepackage&8] &eDropping at your current location...'
TooLittleMoney: '&8[&cCarepackage&8] &eYou do not have the required funds.'
ItemsPerPackage: 5
Cost: 500
Items:
    '1':
        Material: APPLE
        Amount: 10
        Name: '&cMagical Apple'
        Lore:
            - '&eThe magical apple of wisdom'
        Data: 0
        Chance: 100
        Enchant:
            'DURABILITY':
                Value: 5
    '2':
        Material: APPLE
        Amount: 8
        Name: '&1Magical Apple'
        Lore:
            - '&eThe magical apple of wisdom'
        Data: 0
        Chance: 80
        Enchant:
            'DURABILITY':
                Value: 5
    '3':
        Material: APPLE
        Amount: 6
        Name: '&2Magical Apple'
        Lore:
            - '&eThe magical apple of wisdom'
        Data: 0
        Chance: 60
        Enchant:
            'DURABILITY':
                Value: 5
    '4':
        Material: APPLE
        Amount: 4
        Name: '&3Magical Apple'
        Lore:
            - '&eThe magical apple of wisdom'
        Data: 0
        Chance: 40
        Enchant:
            'DURABILITY':
                Value: 5
    '5':
        Material: APPLE
        Amount: 2
        Name: '&4Magical Apple'
        Lore:
            - '&eThe magical apple of wisdom'
        Data: 0
        Chance: 20
        Enchant:
            'DURABILITY':
                Value: 5