Message: '&8[&cCarepackage&8] &eDropping at your current location...'
TooLittleMoney: '&8[&cCarepackage&8] &eYou do not have the required funds.'
ItemsPerPackage: 5
Cost: 500
Items:
    '1':
        Material: DIAMOND_SWORD
        Amount: 10
        Name: '&cMagical Sword'
        Lore:
            - '&eThe magical Sword of wisdom'
        Data: 0
        Chance: 50
        Enchant:
            'DURABILITY':
                Value: 5
            'FIRE_ASPECT':
                Value: 5
    '2':
        Material: APPLE
        Amount: 8
        Name: '&1Magical Apple'
        Lore:
            - '&eThe magical apple of wisdom'
        Data: 0
        Chance: 80
        Enchant:
            'DURABILITY':
                Value: 5
    '3':
        Material: APPLE
        Amount: 6
        Name: '&2Magical Apple'
        Lore:
            - '&eThe magical apple of wisdom'
        Chance: 60
    '4':
        Material: APPLE
        Amount: 4
        Chance: 40
        Enchant:
            'DURABILITY':
                Value: 5
            'FIRE_ASPECT':
                Value: 2
    '5':
        Material: APPLE
        Amount: 2
        Chance: 20